name: runner_extension
description: "A Flutter Desktop App to run other Flutter/Dart Apps."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tray_manager: ^0.3.1
  window_manager: ^0.4.3
  macos_ui: ^2.0.9
  ionicons: ^0.2.2
  equatable: ^2.0.7
  # flutter pub add -d isar_generator build_runner
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  file_picker: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner: ^5.8.0
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/


